# Generated by Django 4.2.30 on 2026-04-18 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0002_auction_auction_type_auction_dutch_decrement'),
        ('bidding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidderRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_flags', models.PositiveIntegerField(default=0)),
                ('collusion_score', models.FloatField(default=0.0, help_text='0–100; higher = more suspicious')),
                ('anomaly_score', models.FloatField(default=0.0, help_text='0–100; higher = more anomalous')),
                ('shill_score', models.FloatField(default=0.0, help_text='0–100; higher = more suspicious')),
                ('last_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-collusion_score'],
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('shill_bid', 'Shill Bidding'), ('collusion', 'Collusion'), ('rate_limit', 'Rate Limit Exceeded'), ('anomaly', 'Bid Anomaly'), ('account_link', 'Linked Account'), ('duplicate_bid', 'Duplicate Bid'), ('rapid_fire', 'Rapid-Fire Bidding'), ('withdrawal_pattern', 'Bid Withdrawal Pattern')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_flags', to='auctions.auction')),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_flags', to='bidding.bid')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_flags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'flag_type'], name='fraud_detec_user_id_be5c9e_idx'), models.Index(fields=['auction'], name='fraud_detec_auction_38e7d6_idx'), models.Index(fields=['is_reviewed'], name='fraud_detec_is_revi_9dda71_idx')],
            },
        ),
    ]
