# Generated by Django 4.2.30 on 2026-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blacklist_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('bidder', 'Bidder'), ('auctioneer', 'Auctioneer'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='bidder', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trust_score',
            field=models.FloatField(default=100.0, help_text='0–100; reduced by fraud flags'),
        ),
    ]
