# Generated by Django 6.0.4 on 2026-04-17 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum proxy bid amount', max_digits=12, null=True)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_auto_bid', models.BooleanField(default=False)),
                ('is_winning', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('outbid', 'Outbid'), ('won', 'Won'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bid_time'],
            },
        ),
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('bid_placed', 'Bid Placed'), ('proxy_bid', 'Proxy Bid'), ('outbid', 'Outbid'), ('reserve_met', 'Reserve Met'), ('auction_started', 'Auction Started'), ('auction_ended', 'Auction Ended'), ('buy_now', 'Buy Now'), ('auto_extend', 'Auto Extended'), ('cancelled', 'Cancelled')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_logs', to='auctions.auction')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProxyBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_bids', to='auctions.auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'auction')},
            },
        ),
    ]
