# Generated by Django 4.2.30 on 2026-04-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_type',
            field=models.CharField(choices=[('english', 'English Auction (Ascending Price)'), ('sealed_bid', 'Sealed-Bid Auction (Highest Wins)'), ('dutch', 'Dutch Auction (Descending Price)'), ('vickrey', 'Vickrey Auction (Second-Price Sealed Bid)')], default='english', help_text='Auction strategy determines winner determination logic', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='dutch_decrement',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price decrement per interval for Dutch auctions', max_digits=12, null=True),
        ),
    ]
