# Generated by Django 4.2.30 on 2026-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_auction_type_auction_dutch_decrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('physical', '🛍️ Physical Items'), ('digital', '💻 Digital Assets'), ('services', '🧑\u200d💼 Services'), ('real_estate', '🏢 Real Estate & Property'), ('tickets', '🎟️ Tickets & Access'), ('education', '🎓 Education & Career'), ('industrial', '🚜 Industrial / B2B'), ('financial', '💡 Financial / Abstract'), ('gaming', '🎮 Entertainment & Gaming'), ('custom', '🧾 Custom / Open Listings'), ('other', 'Other')], db_index=True, default='other', max_length=30),
        ),
    ]
