# Generated by Django 4.2.30 on 2026-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_auction_type_auction_dutch_decrement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('physical', 'Physical Items'), ('digital', 'Digital Assets'), ('services', 'Services'), ('realestate', 'Real Estate & Property'), ('tickets', 'Tickets & Access'), ('education', 'Education & Career'), ('industrial', 'Industrial / B2B'), ('financial', 'Financial / Abstract'), ('entertainment', 'Entertainment & Gaming'), ('custom', 'Custom / Open Listings')], default='physical', help_text='Category group/section', max_length=30),
        ),
    ]
